name: Fast API book project tests

on:
    pull_request:
        branches: [main]


jobs:
    test:

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4
        - name: Set up Python 3.10
          uses: actions/setup-python@v4
          with:
            python-version: "3.10"

        - name: Install dependencies
          run: |
            python -m venv venv
            source venv/bin/activate
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Test with pytest
          run: |
            pytest

        - name: Notify Telex of Test Success
          if: success()
          run: |
            curl -X POST -H "Content-Type: application/json" -d '{
              "event_name": "ci_pipeline_test", 
              "username": "GitHub Actions",
              "status": "success",
              "message": "Tests passed successfully for PR ${{ github.event.pull_request.number }}."
              }' ${{ secrets.TELEX_WEBHOOK_URL }}
                    
        - name: Notify Telex of Test Failure
          if: failure()
          run: |
            curl -X POST -H "Content-Type: application/json" -d '{
              "event_name": "ci_pipeline_test", 
              "username": "GitHub Actions",
              "status": "failure",
              "message": "Tests failed for PR ${{ github.event.pull_request.number }}."
              }' ${{ secrets.TELEX_WEBHOOK_URL}}
                  

